version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.production

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3001:3001"
      - "9001:9001"

  customer:
    build:
      context: .
      dockerfile: ./apps/customer/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3002:3002"

  business:
    build:
      context: .
      dockerfile: ./apps/business/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3003:3003"

  category:
    build:
      context: .
      dockerfile: ./apps/category/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3004:3004"

  attribute:
    build:
      context: .
      dockerfile: ./apps/attribute/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3005:3005"

  discount:
    build:
      context: .
      dockerfile: ./apps/discount/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3006:3006"

  product:
    build:
      context: .
      dockerfile: ./apps/product/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3007:3007"

  order:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3008:3008"

  cart:
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3009:3009"

  mail:
    build:
      context: .
      dockerfile: ./apps/mail/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "9010:9010"

  payment:
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "9011:9011"

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production
    env_file:
      - .env.production
    ports:
      - "3000:3000"
